services:
  shoofly_doctrine_multi_schema.platform:
      class: Shoofly\DoctrineMultiSchemaBundle\DBAL\MySql\Platform
      calls:
        - [setSchemas, "%shoofly.doctrine_multi_schema.schemas%"]
  shoofly_doctrine_multi_schema.platform57:
      class: Shoofly\DoctrineMultiSchemaBundle\DBAL\MySql\Platform57
      calls:
        - [setSchemas, "%shoofly.doctrine_multi_schema.schemas%"]
  shoofly_doctrine_multi_schema.listeners.schemas:
      class: Shoofly\DoctrineMultiSchemaBundle\Listeners\DoctrineSchemasSubscriber
      arguments: ["%shoofly.doctrine_multi_schema.schemas%"]
      tags:
        - { name: doctrine.event_subscriber, connection: default  }
