services:
  shoofly_doctrine_multi_schema.listeners.schemas:
      class: Shoofly\DoctrineMultiSchemaBundle\Listeners\DoctrineSchemasSubscriber
      arguments: ["%shoofly.doctrine_multi_schema.schemas%"]
      tags:
        - { name: doctrine.event_subscriber, connection: default  }
